version: '3.1'  # if no version is specified then v1 is assumed. Recommend v2 minimum

services:
  drupalcontainer: # a friendly name. this is also DNS name inside network
    image: drupal  # Optional if you use build:
    ports: 
        - 8080:8080
    #volumes: Optional, same as -v in docker run
  mysqldatabase:
    image: postgres
    ports: 
        - 8080:8080
    environment:
        - POSTGRES_PASSWORD: mypassword

